name: 'Slack POST Message with Slack API'
author: 'goldeneggg'
description: 'My slack post message action'

# See: https://help.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs
inputs:
  bot_token:
    description: 'Bot token'
    required: true
  channel_id:
    description: 'Target channel id'
    required: true
  text:
    description: 'Posted text'
    required: true

# See: https://help.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs
outputs:
  ok:
    description: '"ok" slack response (true is success, false is failure)'
  response_metadata:
    description: '"response_metadata" slack response'

runs:
  # for JavaScript  See: https://help.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions
  #using: 'node12'
  #pre: 'setup.js'
  #pre-if: 'runner.os == linux'
  #main: 'main.js'
  #post: 'cleanup.js'
  #post-if: 'runner.os == linux'

  # for Docker  See: https://help.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-docker-actions
  using: 'docker'
  image: 'Dockerfile'
  #image: 'docker://debian:stetch-slim'
  args:
    - ${{ inputs.channel_id }}
  #pre-entrypoint: '/app/setup.sh'
  #pre-if: 'runner.os == linux'
  #entrypoint: 'entrypoint.sh'
  #env:
    #ACTION_ENV: action_env
  #post-entrypoint: '/app/cleanup.sh'
  #post-if: 'runner.os == linux'

# See: https://help.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding
#branding:
  #icon: 'award'  
  #color: 'green'
