name: 'Hogeo Hugao sh'
author: 'goldeneggg'
description: 'My local docker action Hoge Huga sh'

# See: https://help.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs
inputs:
  aho:
    description: 'Aho input'
    required: true
    default: 'Huga-sh'

# See: https://help.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs
outputs:
  time:
    description: 'The time we greeted you'

runs:
  # for JavaScript  See: https://help.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions
  #using: 'node12'
  #pre: 'setup.js'
  #pre-if: 'runner.os == linux'
  #main: 'main.js'
  #post: 'cleanup.js'
  #post-if: 'runner.os == linux'

  # for Docker  See: https://help.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-docker-actions
  using: 'docker'
  image: 'Dockerfile'
  #image: 'docker://debian:stetch-slim'
  args:
    - ${{ inputs.aho }}
  #pre-entrypoint: 'setup.sh'
  #pre-if: 'runner.os == linux'
  #entrypoint: 'entrypoint.sh'
  #env:
    #ACTION_ENV: action_env
  #post-entrypoint: 'cleanup.pt'
  #post-if: 'runner.os == linux'

# See: https://help.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding
#branding:
  #icon: 'award'  
  #color: 'green'
