on:
  pull_request:

env:
  HOGE: pr_hoge_global

jobs:
  job-debug:
    name: Job debug
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"


  job1:
    name: Job1
    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.step1.outputs.output-step1 }}
      output2: ${{ steps.step2.outputs.output-step2 }}

    steps:
    - id: step1
      run: echo "::set-output name=output-step1::pr"
    - id: step2
      run: echo "::set-output name=output-step2::triggered"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}



# TODO: GitHub APIを呼ぶ実験 with github-script



# TODO: Slack通知実験



# TODO: AWS連携 実験



  # macosとubuntuで実行するジョブの実験
  job-mac-ubuntu:
    name: Job with Mac and Ubuntu
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'macos-latest', 'ubuntu-latest' ]
      fail-fast: false

    outputs:
      output1: ${{ steps.step1.outputs.output-step1 }}
      output2: ${{ steps.step2.outputs.output-step2 }}

    steps:
    - id: step1
      run: echo "::set-output name=output-step1::hello"
    - id: step2
      run: echo "::set-output name=output-step2::world"








# TODO: Google Drive APIを呼ぶ実験
