on:
  push:
    branches:
      - master

env:
  HOGE: push_master_hoge_global

jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.step1.outputs.output-step1 }}
      output2: ${{ steps.step2.outputs.output-step2 }}

    steps:
    - id: step1
      run: echo "::set-output name=output-step1::push_master"

    - id: step2
      run: echo "::set-output name=output-step2::triggered"

    - id: checkout
      uses: actions/checkout@v2

    # TODO:
    # 1. ベンチマーク結果をルートフォルダ直下に作成してpushする
    # 2. 1 を含めて、新規release をdraft で作成する
    - id: create-benchmark-report
      name: Create benchmark report
      run: date +%s > BENCHMARK_MASTER.txt

    # See: https://stackoverflow.com/questions/57921401/push-to-origin-from-github-action
    - id: commit-push-report
      name: Commit and push benchmark report
      run: |
        git config --global user.name 'goldeneggg'
        git config --global user.email 'jpshadowapps@gmail.com'
        git commit -am "Automated update benchmark report"
        git push

    - id: create-release
      name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: true
        prerelease: false

    - id: dump-contexts-after
      name: Dump contexts (After)
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        JOB_CONTEXT: ${{ toJson(job) }}
        STEPS_CONTEXT: ${{ toJson(steps) }}
        RUNNER_CONTEXT: ${{ toJson(runner) }}
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      if: ${{ always() }}
      run: |
        echo ">>>>>>>>>> show GITHUB_CONTEXT"
        echo "$GITHUB_CONTEXT"
        echo ">>>>>>>>>> show JOB_CONTEXT"
        echo "$JOB_CONTEXT"
        echo ">>>>>>>>>> show STEPS_CONTEXT"
        echo "$STEPS_CONTEXT"
        echo ">>>>>>>>>> show RUNNER_CONTEXT"
        echo "$RUNNER_CONTEXT"
        echo ">>>>>>>>>> show STRATEGY_CONTEXT"
        echo "$STRATEGY_CONTEXT"
        echo ">>>>>>>>>> show MATRIX_CONTEXT"
        echo "$MATRIX_CONTEXT"
