on:
  push:
    branches:
      - master

env:
  HOGE: push_master_hoge_global

jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.step1.outputs.output-step1 }}
      output2: ${{ steps.step2.outputs.output-step2 }}

    steps:
    - id: step1
      run: echo "::set-output name=output-step1::push_master"

    - id: step2
      run: echo "::set-output name=output-step2::triggered"

    - id: checkout
      uses: actions/checkout@v2

    # TODO:
    # 1. ベンチマーク結果（注: このaction例はダミーのファイルにしてある）をルートフォルダ直下に作成してpushする
    # 2. 1 を含めて、新規release をdraft で作成する
    - id: create-benchmark-report
      name: create benchmark report
      run: date +%s > BENCHMARK_MASTER.txt

    # See: https://stackoverflow.com/questions/57921401/push-to-origin-from-github-action
    # masterブランチへの保護設定を掛けていると失敗するので、保護してるプロジェクトでは別途対応が必要
    - id: commit-push-report
      name: commit and push benchmark report
      run: |
        pwd
        ls -l
        git config --global user.name 'goldeneggg'
        git config --global user.email 'jpshadowapps@gmail.com'
        git add BENCHMARK_MASTER.txt
        git commit -m "Automated update benchmark report"
        git push

    # draft releaseを作成（draftなので最終的なrelease publishはgithubのweb画面から実施する）
    - id: create-release
      name: create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: true
        prerelease: false

    ### AWS
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    # s3へのsync（リポジトリ全体）
    # （対象IAMにS3へのアクセスポリシー（AmazonS3FullAccess）を付与しておき、バケットとバケット内フォルダは事前に作成しておくこと）
    - id: sync-s3-whole
      name: Sync repositry contents to S3
      env:
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
      run: |
        aws s3 sync ./ s3://$S3_BUCKET/actions-experimental --exclude '.git/*' --exclude '.envrc' --exclude '.env' --quiet

    - id: dump-contexts-after
      name: Dump contexts (After)
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        JOB_CONTEXT: ${{ toJson(job) }}
        STEPS_CONTEXT: ${{ toJson(steps) }}
        RUNNER_CONTEXT: ${{ toJson(runner) }}
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      if: ${{ always() }}
      run: |
        echo ">>>>>>>>>> show GITHUB_CONTEXT"
        echo "$GITHUB_CONTEXT"
        echo ">>>>>>>>>> show JOB_CONTEXT"
        echo "$JOB_CONTEXT"
        echo ">>>>>>>>>> show STEPS_CONTEXT"
        echo "$STEPS_CONTEXT"
        echo ">>>>>>>>>> show RUNNER_CONTEXT"
        echo "$RUNNER_CONTEXT"
        echo ">>>>>>>>>> show STRATEGY_CONTEXT"
        echo "$STRATEGY_CONTEXT"
        echo ">>>>>>>>>> show MATRIX_CONTEXT"
        echo "$MATRIX_CONTEXT"
