on:
  # See: https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule
  schedule:
    # 毎日9時
    - cron:  '0 9 * * *'

env:
  HOGE: schedule_hoge_global

jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.step1.outputs.output-step1 }}
      output2: ${{ steps.step2.outputs.output-step2 }}

    steps:
    - id: step1
      run: echo "::set-output name=output-step1::schedule"
    - id: step2
      run: echo "::set-output name=output-step2::triggered"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}

    - id: dump-contexts-after
      name: Dump contexts (After)
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        JOB_CONTEXT: ${{ toJson(job) }}
        STEPS_CONTEXT: ${{ toJson(steps) }}
        RUNNER_CONTEXT: ${{ toJson(runner) }}
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: |
        echo ">>>>>>>>>> show GITHUB_CONTEXT"
        echo "$GITHUB_CONTEXT"
        echo ">>>>>>>>>> show JOB_CONTEXT"
        echo "$JOB_CONTEXT"
        echo ">>>>>>>>>> show STEPS_CONTEXT"
        echo "$STEPS_CONTEXT"
        echo ">>>>>>>>>> show RUNNER_CONTEXT"
        echo "$RUNNER_CONTEXT"
        echo ">>>>>>>>>> show STRATEGY_CONTEXT"
        echo "$STRATEGY_CONTEXT"
        echo ">>>>>>>>>> show MATRIX_CONTEXT"
        echo "$MATRIX_CONTEXT"
